[2024-02-05T07:22:06.794+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T07:22:04.711771+00:00 [queued]>
[2024-02-05T07:22:06.808+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T07:22:04.711771+00:00 [queued]>
[2024-02-05T07:22:06.809+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T07:22:06.809+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-02-05T07:22:06.810+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T07:22:06.826+0000] {taskinstance.py:1389} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-02-05 07:22:04.711771+00:00
[2024-02-05T07:22:06.832+0000] {standard_task_runner.py:52} INFO - Started process 52522 to run task
[2024-02-05T07:22:06.835+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'sqlite_randomuser', 'is_api_available', 'manual__2024-02-05T07:22:04.711771+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/sqlite_randomuser.py', '--cfg-path', '/tmp/tmp1g59gxdp', '--error-file', '/tmp/tmphepaplqy']
[2024-02-05T07:22:06.836+0000] {standard_task_runner.py:80} INFO - Job 18: Subtask is_api_available
[2024-02-05T07:22:06.905+0000] {task_command.py:371} INFO - Running <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T07:22:04.711771+00:00 [running]> on host fe2863c78e2f
[2024-02-05T07:22:06.991+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sqlite_randomuser
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-02-05T07:22:04.711771+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-05T07:22:04.711771+00:00
[2024-02-05T07:22:06.992+0000] {http.py:120} INFO - Poking: api/
[2024-02-05T07:22:07.002+0000] {base.py:68} INFO - Using connection ID 'randomuser_api' for task execution.
[2024-02-05T07:22:07.004+0000] {http.py:148} INFO - Sending 'GET' to url: http://randomuser.me/api/
[2024-02-05T07:22:07.937+0000] {base.py:301} INFO - Success criteria met. Exiting.
[2024-02-05T07:22:07.952+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=sqlite_randomuser, task_id=is_api_available, execution_date=20240205T072204, start_date=20240205T072206, end_date=20240205T072207
[2024-02-05T07:22:07.979+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-05T07:22:08.026+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
