[2024-02-05T08:26:14.352+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T08:26:12.530105+00:00 [queued]>
[2024-02-05T08:26:14.365+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T08:26:12.530105+00:00 [queued]>
[2024-02-05T08:26:14.366+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T08:26:14.367+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-02-05T08:26:14.367+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T08:26:14.385+0000] {taskinstance.py:1389} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-02-05 08:26:12.530105+00:00
[2024-02-05T08:26:14.392+0000] {standard_task_runner.py:52} INFO - Started process 162051 to run task
[2024-02-05T08:26:14.395+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'sqlite_randomuser', 'is_api_available', 'manual__2024-02-05T08:26:12.530105+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/sqlite_randomuser.py', '--cfg-path', '/tmp/tmp_m13kg17', '--error-file', '/tmp/tmpdovwa84p']
[2024-02-05T08:26:14.396+0000] {standard_task_runner.py:80} INFO - Job 29: Subtask is_api_available
[2024-02-05T08:26:14.474+0000] {task_command.py:371} INFO - Running <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T08:26:12.530105+00:00 [running]> on host fe2863c78e2f
[2024-02-05T08:26:14.580+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sqlite_randomuser
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-02-05T08:26:12.530105+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-05T08:26:12.530105+00:00
[2024-02-05T08:26:14.582+0000] {http.py:120} INFO - Poking: api/
[2024-02-05T08:26:14.593+0000] {base.py:68} INFO - Using connection ID 'randomuser_api' for task execution.
[2024-02-05T08:26:14.596+0000] {http.py:148} INFO - Sending 'GET' to url: http://randomuser.me/api/
[2024-02-05T08:26:15.595+0000] {base.py:301} INFO - Success criteria met. Exiting.
[2024-02-05T08:26:15.610+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=sqlite_randomuser, task_id=is_api_available, execution_date=20240205T082612, start_date=20240205T082614, end_date=20240205T082615
[2024-02-05T08:26:15.825+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-05T08:26:15.889+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
