[2024-02-05T07:21:03.480+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.extracting_user manual__2024-02-05T07:20:59.166302+00:00 [queued]>
[2024-02-05T07:21:03.492+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.extracting_user manual__2024-02-05T07:20:59.166302+00:00 [queued]>
[2024-02-05T07:21:03.492+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T07:21:03.493+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-02-05T07:21:03.493+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T07:21:03.507+0000] {taskinstance.py:1389} INFO - Executing <Task(SimpleHttpOperator): extracting_user> on 2024-02-05 07:20:59.166302+00:00
[2024-02-05T07:21:03.513+0000] {standard_task_runner.py:52} INFO - Started process 50963 to run task
[2024-02-05T07:21:03.516+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'sqlite_randomuser', 'extracting_user', 'manual__2024-02-05T07:20:59.166302+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/sqlite_randomuser.py', '--cfg-path', '/tmp/tmpng_k1s1u', '--error-file', '/tmp/tmpu1gakx8j']
[2024-02-05T07:21:03.517+0000] {standard_task_runner.py:80} INFO - Job 16: Subtask extracting_user
[2024-02-05T07:21:03.579+0000] {task_command.py:371} INFO - Running <TaskInstance: sqlite_randomuser.extracting_user manual__2024-02-05T07:20:59.166302+00:00 [running]> on host fe2863c78e2f
[2024-02-05T07:21:03.655+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sqlite_randomuser
AIRFLOW_CTX_TASK_ID=extracting_user
AIRFLOW_CTX_EXECUTION_DATE=2024-02-05T07:20:59.166302+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-05T07:20:59.166302+00:00
[2024-02-05T07:21:03.656+0000] {http.py:121} INFO - Calling HTTP method
[2024-02-05T07:21:03.666+0000] {base.py:68} INFO - Using connection ID 'randomuser_api' for task execution.
[2024-02-05T07:21:03.668+0000] {http.py:148} INFO - Sending 'GET' to url: http://randomuser.me/api/
[2024-02-05T07:21:08.653+0000] {http.py:125} INFO - {"results":[{"gender":"female","name":{"title":"Miss","first":"آوا","last":"زارعی"},"location":{"street":{"number":9567,"name":"شورا"},"city":"اراک","state":"چهارمحال و بختیاری","country":"Iran","postcode":10184,"coordinates":{"latitude":"19.8083","longitude":"127.4118"},"timezone":{"offset":"-1:00","description":"Azores, Cape Verde Islands"}},"email":"aw.zraay@example.com","login":{"uuid":"0446f80c-060e-4ce6-bec6-59a4ab47586e","username":"heavyfrog638","password":"rhodes","salt":"yb6W6zE4","md5":"7c7b3fc01e0c7e8ea8afbb0638e01fd3","sha1":"ac945d8441e2f99704e93bb1251b3c6da299bfef","sha256":"df6a464dd3c29c9a9f6caad09e9162d83d889f95f0a5774def2ab9258e4f197b"},"dob":{"date":"1981-04-15T09:10:13.134Z","age":42},"registered":{"date":"2007-09-11T18:58:05.075Z","age":16},"phone":"072-43548797","cell":"0994-126-9823","id":{"name":"","value":null},"picture":{"large":"https://randomuser.me/api/portraits/women/64.jpg","medium":"https://randomuser.me/api/portraits/med/women/64.jpg","thumbnail":"https://randomuser.me/api/portraits/thumb/women/64.jpg"},"nat":"IR"}],"info":{"seed":"03913ab37d74bf87","results":1,"page":1,"version":"1.4"}}
[2024-02-05T07:21:08.654+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 132, in execute
    return self.response_filter(response, **kwargs)
  File "/opt/airflow/dags/sqlite_randomuser.py", line 49, in <lambda>
    response_filter=lambda response: response.json()['results'][0]['user'],
KeyError: 'user'
[2024-02-05T07:21:08.669+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=sqlite_randomuser, task_id=extracting_user, execution_date=20240205T072059, start_date=20240205T072103, end_date=20240205T072108
[2024-02-05T07:21:08.681+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 16 for task extracting_user ('user'; 50963)
[2024-02-05T07:21:08.709+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-05T07:21:08.733+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
