[2024-02-06T02:28:12.341+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.creating_table scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-02-06T02:28:12.393+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.creating_table scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-02-06T02:28:12.394+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-02-06T02:28:12.395+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-02-06T02:28:12.395+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-02-06T02:28:12.496+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): creating_table> on 2024-02-05 00:00:00+00:00
[2024-02-06T02:28:12.503+0000] {standard_task_runner.py:52} INFO - Started process 208 to run task
[2024-02-06T02:28:12.508+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'sqlite_randomuser', 'creating_table', 'scheduled__2024-02-05T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/sqlite_randomuser.py', '--cfg-path', '/tmp/tmpkwd1iv8d', '--error-file', '/tmp/tmp_nd9i2hb']
[2024-02-06T02:28:12.511+0000] {standard_task_runner.py:80} INFO - Job 76: Subtask creating_table
[2024-02-06T02:28:12.807+0000] {task_command.py:371} INFO - Running <TaskInstance: sqlite_randomuser.creating_table scheduled__2024-02-05T00:00:00+00:00 [running]> on host 0f884a2e3c33
[2024-02-06T02:28:13.295+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sqlite_randomuser
AIRFLOW_CTX_TASK_ID=creating_table
AIRFLOW_CTX_EXECUTION_DATE=2024-02-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-05T00:00:00+00:00
[2024-02-06T02:28:13.309+0000] {base.py:68} INFO - Using connection ID '***_postgres' for task execution.
[2024-02-06T02:28:13.314+0000] {sql.py:315} INFO - Running statement: CREATE TABLE IF NOT EXISTS users(
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY), parameters: None
[2024-02-06T02:28:13.317+0000] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2024-02-06T02:28:13.336+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=sqlite_randomuser, task_id=creating_table, execution_date=20240205T000000, start_date=20240206T022812, end_date=20240206T022813
[2024-02-06T02:28:13.362+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-06T02:28:13.574+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
