[2024-02-05T09:00:33.283+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T09:00:31.263732+00:00 [queued]>
[2024-02-05T09:00:33.295+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T09:00:31.263732+00:00 [queued]>
[2024-02-05T09:00:33.295+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T09:00:33.296+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-02-05T09:00:33.296+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T09:00:33.310+0000] {taskinstance.py:1389} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-02-05 09:00:31.263732+00:00
[2024-02-05T09:00:33.317+0000] {standard_task_runner.py:52} INFO - Started process 284529 to run task
[2024-02-05T09:00:33.319+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'sqlite_randomuser', 'is_api_available', 'manual__2024-02-05T09:00:31.263732+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/sqlite_randomuser.py', '--cfg-path', '/tmp/tmpeqjcelb3', '--error-file', '/tmp/tmpp_mrwj3u']
[2024-02-05T09:00:33.320+0000] {standard_task_runner.py:80} INFO - Job 33: Subtask is_api_available
[2024-02-05T09:00:33.380+0000] {task_command.py:371} INFO - Running <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T09:00:31.263732+00:00 [running]> on host fe2863c78e2f
[2024-02-05T09:00:33.451+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sqlite_randomuser
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-02-05T09:00:31.263732+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-05T09:00:31.263732+00:00
[2024-02-05T09:00:33.452+0000] {http.py:120} INFO - Poking: api/
[2024-02-05T09:00:33.461+0000] {base.py:68} INFO - Using connection ID 'randomuser_api' for task execution.
[2024-02-05T09:00:33.463+0000] {http.py:148} INFO - Sending 'GET' to url: http://randomuser.me/api/
[2024-02-05T09:00:33.926+0000] {base.py:301} INFO - Success criteria met. Exiting.
[2024-02-05T09:00:33.942+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=sqlite_randomuser, task_id=is_api_available, execution_date=20240205T090031, start_date=20240205T090033, end_date=20240205T090033
[2024-02-05T09:00:34.148+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-05T09:00:34.195+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
