[2024-02-05T20:43:31.505+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T20:43:29.240857+00:00 [queued]>
[2024-02-05T20:43:31.517+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T20:43:29.240857+00:00 [queued]>
[2024-02-05T20:43:31.518+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T20:43:31.518+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-02-05T20:43:31.519+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T20:43:31.535+0000] {taskinstance.py:1389} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-02-05 20:43:29.240857+00:00
[2024-02-05T20:43:31.542+0000] {standard_task_runner.py:52} INFO - Started process 339914 to run task
[2024-02-05T20:43:31.544+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'sqlite_randomuser', 'is_api_available', 'manual__2024-02-05T20:43:29.240857+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/sqlite_randomuser.py', '--cfg-path', '/tmp/tmp_howc0kr', '--error-file', '/tmp/tmpiedqqvl5']
[2024-02-05T20:43:31.546+0000] {standard_task_runner.py:80} INFO - Job 70: Subtask is_api_available
[2024-02-05T20:43:31.612+0000] {task_command.py:371} INFO - Running <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T20:43:29.240857+00:00 [running]> on host fe2863c78e2f
[2024-02-05T20:43:31.691+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sqlite_randomuser
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-02-05T20:43:29.240857+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-05T20:43:29.240857+00:00
[2024-02-05T20:43:31.692+0000] {http.py:120} INFO - Poking: api/
[2024-02-05T20:43:31.702+0000] {base.py:68} INFO - Using connection ID 'randomuser_api' for task execution.
[2024-02-05T20:43:31.704+0000] {http.py:148} INFO - Sending 'GET' to url: http://randomuser.me/api/
[2024-02-05T20:43:32.220+0000] {base.py:301} INFO - Success criteria met. Exiting.
[2024-02-05T20:43:32.237+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=sqlite_randomuser, task_id=is_api_available, execution_date=20240205T204329, start_date=20240205T204331, end_date=20240205T204332
[2024-02-05T20:43:32.279+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-05T20:43:32.335+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
