[2024-02-06T03:45:08.549+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: nyctaxi_elt.fetch_data manual__2024-02-06T03:45:05.816229+00:00 [queued]>
[2024-02-06T03:45:08.568+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: nyctaxi_elt.fetch_data manual__2024-02-06T03:45:05.816229+00:00 [queued]>
[2024-02-06T03:45:08.569+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-02-06T03:45:08.569+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-02-06T03:45:08.570+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-02-06T03:45:08.599+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-02-06 03:45:05.816229+00:00
[2024-02-06T03:45:08.615+0000] {standard_task_runner.py:52} INFO - Started process 1633 to run task
[2024-02-06T03:45:08.616+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyctaxi_elt', 'fetch_data', 'manual__2024-02-06T03:45:05.816229+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/nyctaxi_elt.py', '--cfg-path', '/tmp/tmpq7_99ybm', '--error-file', '/tmp/tmpuf9hyg68']
[2024-02-06T03:45:08.618+0000] {standard_task_runner.py:80} INFO - Job 10: Subtask fetch_data
[2024-02-06T03:45:08.686+0000] {task_command.py:371} INFO - Running <TaskInstance: nyctaxi_elt.fetch_data manual__2024-02-06T03:45:05.816229+00:00 [running]> on host 9d3dd91d9998
[2024-02-06T03:45:08.766+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyctaxi_elt
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-02-06T03:45:05.816229+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-06T03:45:05.816229+00:00
[2024-02-06T03:45:10.243+0000] {nyctaxi_elt.py:48} INFO -     vendorid     lpep_pickup_datetime  ... trip_type congestion_surcharge
0          2  2021-01-01T00:15:56.000  ...         1                    0
1          2  2021-01-01T00:25:59.000  ...         1                 2.75
2          2  2021-01-01T00:45:57.000  ...         1                    0
3          2  2020-12-31T23:57:51.000  ...         1                    0
4          2  2021-01-01T00:16:36.000  ...         1                    0
..       ...                      ...  ...       ...                  ...
995        2  2021-01-02T12:59:36.000  ...         1                    0
996        2  2021-01-02T13:00:05.000  ...         1                 2.75
997        2  2021-01-02T12:48:43.000  ...         1                    0
998        1  2021-01-02T12:16:47.000  ...         1                    0
999        2  2021-01-02T12:07:17.000  ...         1                    0

[1000 rows x 19 columns]
[2024-02-06T03:45:10.297+0000] {python.py:173} INFO - Done. Returned value was:     vendorid     lpep_pickup_datetime  ... trip_type congestion_surcharge
0          2  2021-01-01T00:15:56.000  ...         1                    0
1          2  2021-01-01T00:25:59.000  ...         1                 2.75
2          2  2021-01-01T00:45:57.000  ...         1                    0
3          2  2020-12-31T23:57:51.000  ...         1                    0
4          2  2021-01-01T00:16:36.000  ...         1                    0
..       ...                      ...  ...       ...                  ...
995        2  2021-01-02T12:59:36.000  ...         1                    0
996        2  2021-01-02T13:00:05.000  ...         1                 2.75
997        2  2021-01-02T12:48:43.000  ...         1                    0
998        1  2021-01-02T12:16:47.000  ...         1                    0
999        2  2021-01-02T12:07:17.000  ...         1                    0

[1000 rows x 19 columns]
[2024-02-06T03:45:10.321+0000] {xcom.py:586} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-02-06T03:45:10.322+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2405, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 198, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2024-02-06T03:45:10.338+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=nyctaxi_elt, task_id=fetch_data, execution_date=20240206T034505, start_date=20240206T034508, end_date=20240206T034510
[2024-02-06T03:45:10.349+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task fetch_data (Object of type DataFrame is not JSON serializable; 1633)
[2024-02-06T03:45:10.358+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-06T03:45:10.387+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
