[2024-02-05T09:21:46.101+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T09:21:42.132520+00:00 [queued]>
[2024-02-05T09:21:46.119+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T09:21:42.132520+00:00 [queued]>
[2024-02-05T09:21:46.120+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T09:21:46.121+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2024-02-05T09:21:46.122+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-02-05T09:21:46.146+0000] {taskinstance.py:1389} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-02-05 09:21:42.132520+00:00
[2024-02-05T09:21:46.152+0000] {standard_task_runner.py:52} INFO - Started process 326424 to run task
[2024-02-05T09:21:46.155+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'sqlite_randomuser', 'is_api_available', 'manual__2024-02-05T09:21:42.132520+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/sqlite_randomuser.py', '--cfg-path', '/tmp/tmp3v0olx10', '--error-file', '/tmp/tmp4n5juok2']
[2024-02-05T09:21:46.158+0000] {standard_task_runner.py:80} INFO - Job 43: Subtask is_api_available
[2024-02-05T09:21:46.271+0000] {task_command.py:371} INFO - Running <TaskInstance: sqlite_randomuser.is_api_available manual__2024-02-05T09:21:42.132520+00:00 [running]> on host fe2863c78e2f
[2024-02-05T09:21:46.420+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sqlite_randomuser
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-02-05T09:21:42.132520+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-05T09:21:42.132520+00:00
[2024-02-05T09:21:46.421+0000] {http.py:120} INFO - Poking: api/
[2024-02-05T09:21:46.438+0000] {base.py:68} INFO - Using connection ID 'randomuser_api' for task execution.
[2024-02-05T09:21:46.441+0000] {http.py:148} INFO - Sending 'GET' to url: http://randomuser.me/api/
[2024-02-05T09:21:47.402+0000] {base.py:301} INFO - Success criteria met. Exiting.
[2024-02-05T09:21:47.428+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=sqlite_randomuser, task_id=is_api_available, execution_date=20240205T092142, start_date=20240205T092146, end_date=20240205T092147
[2024-02-05T09:21:47.685+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-05T09:21:47.772+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
